apiVersion: v1
kind: ServiceAccount
metadata:
  name: appdynamics-infraviz
  namespace: appdynamics
---
apiVersion: cluster.appdynamics.com/v1alpha1
kind: InfraViz
metadata:
  name: appdynamics-infraviz
  namespace: appdynamics
spec:
  controllerUrl: "https://ptfwdindonesia-prod.saas.appdynamics.com"
  image: "128462065683.dkr.ecr.ap-southeast-3.amazonaws.com/appdynamics/machine-agent:25.1.0"
  imagePullSecret: "aws-registry-prd"
  proxyUrl: "http://165.225.116.10:80"
  account: "ptfwdindonesia-prod"
  enableContainerHostId: true
  enableServerViz: true
  resources:
    limits:
      cpu: 500m
      memory: "1G"
    requests:
      cpu: 200m
      memory: "800M"
